/* this file automatically generated by the Makefile */
#define COMPILER "gcc"
#define OPTIMIZE "-pthread -O2 -pipe -DFD_SETSIZE=10000 -Wall -D_THREAD_SAFE -fstrength-reduce"
#define CFLAGS   "-g3  -I. -Iinclude -Igrammar -I/usr/include/ -I/usr/local/include -I/usr/lib/gcc/x86_64-redhat-linux/4.4.4/include -I/usr/local/ssl/include/ -I/usr/include/apr-1/"
#define OBJDIR   "obj"
#define GAME_MODULE 1
