// 定制的options
// -------------------------------------------
// 注意:packages的数量不能超过100
// -------------------------------------------
#include "grammar/options.h"
#include "include/cc.h"
#define PACKAGE_CONTRIB
#define PACKAGE_DEVELOP
#define PACKAGE_EXAMPLE_LIB
#define PACKAGE_MATH
