{
	"__OPTIMIZE__", " \"-pthread -O2 -pipe -DFD_SETSIZE=10000 -Wall -D_THREAD_SAFE -fstrength-reduce\"",
	"__CFG_MAX_LOCAL_VARIABLES__", "		100",
	"__CALLOUT_HANDLES__", " ",
	"__SAVE_EXTENSION__", " \".o\"",
	"__DEFAULT_PRAGMAS__", " PRAGMA_WARNINGS|PRAGMA_STRICT_TYPES|PRAGMA_SAVE_BINARY|PRAGMA_OPTIMIZE|PRAGMA_ERROR_CONTEXT",
	"__PACKAGE_EXAMPLE_LIB__", " ",
	"__CONFIG_FILE_DIR__", " \"/home/QTZE/script\"",
	"__HEARTBEAT_INTERVAL__", " 2000000",
	"__SYSMALLOC__", " ",
	"__ARRAY_STATS__", " ",
	"__PACKAGE_CONTRIB__", " ",
	"__SMALL_STRING_SIZE__", "     100",
	"__HEART_BEAT_CHUNK__", "      32",
	"__OBJDIR__", "   \"obj\"",
	"__CLASS_STATS__", " ",
	"__LARGE_STRING_SIZE__", "     1000",
	"__APPLY_CACHE_BITS__", " 11",
	"__BINARIES__", " ",
	"__STRING_STATS__", " ",
	"__NO_ANSI__", " ",
	"__CFG_MAX_CALL_DEPTH__", "		100",
	"__LOG_CATCHES__", " ",
	"__MAX_SAVE_SVALUE_DEPTH__", " 25",
	"__CFG_EVALUATOR_STACK_SIZE__", " 	20000",
	"__GAME_MODULE__", " 1",
	"__CFG_LIVING_HASH_SIZE__", "		256",
	"__NONINTERACTIVE_STDERR_WRITE__", " ",
	"__MESSAGE_BUFFER_SIZE__", " 4096",
	"__CFLAGS__", "   \"-g3  -I. -Iinclude -Igrammar -I/usr/include/ -I/usr/local/include -I/usr/lib/gcc/x86_64-redhat-linux/4.4.4/include -I/usr/local/ssl/include/ -I/usr/include/apr-1/\"",
	"__STRIP_BEFORE_PROCESS_INPUT__", " ",
	"__NO_SHADOWS__", " ",
	"__TRAP_CRASHES__", " ",
	"__COMPILER__", " \"gcc\"",
	"__LARGEST_PRINTABLE_STRING__", " 10240",
	"__PACKAGE_DEVELOP__", " ",
	"__COMMAND_BUF_SIZE__", "      2000",
	"__BUFFER_STATS__", " ",
	"__PACKAGE_MATH__", " ",
	"__CFG_COMPILER_STACK_SIZE__", "		400",
};

#define NUM_OPTION_DEFS 39

